version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  app:
    build:
      context: ./app
    image: docker-rag_app
    container_name: rag-app
    ports:
      - "5000:5000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434
    volumes:
      - ./app:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  ollama_data:
