name: rag-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - faiss-gpu
  - pip
  - pip:
      - flask
      - langchain
      - torch
      - torchvision
      - torchaudio
      - langgraph
      - langchain-community
      - langchain-openai
      - huggingface-hub
      - transformers
      - sentence-transformers
      - tavily-python
      - typing-extensions
      - langchain-huggingface
      - langchain-ollama
      - langchain-tavily
      - jq
      - rank_bm25
      - python-dotenv